import Head from 'next/head'

// components
import HomeContents from '@/content/Home'

export default function Home({ products }) {

  return (
    <>
      <Head>
        <title>Ecommerce-Store</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents products={products} />
    </>
  )
}


export async function getServerSideProps() {

  const response = await fetch('https://fakestoreapi.com/products');

  const products = await response.json();

  return {
    props: {
      products,
    },
  };


}
