import Head from 'next/head'

import { useRouter } from 'next/router';

// components
import HomeContents from '@/content/Home'

import { useEffect } from 'react';



export default function Home({ products }) {





  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContents products={products} />
    </>
  )
}


export async function getServerSideProps() {

  const response = await fetch('https://fakestoreapi.com/products');

  const products = await response.json();

  return {
    props: {
      products,
    },
  };


}
